### ISSUE TITLE
To do (Style Stuff)

### ISSUE THREAD

**Issue by seanvree** [seanvree/Monitorr#15]
1) Spacing of tiles - Need to somehow define relative spacing to browser window (like the old .HTML version was)  See below.  IF you have a lot of tiles, it looks fine, but if you only have a few and are viewing the page on wide zoom config, it looks bad...too much padding

![image](https://user-images.githubusercontent.com/8906637/30512073-3dce40ee-9a9b-11e7-84e3-edf69f7a4d46.png)

2) Need offline link function (I really think this is a good feature. I know not everyone uses uptime robot, but if the service is offline, need to send the request to some type of user-defined offline page, in fact, we can make a very simple one as a default / place holder that will live in the repo base DIR, and the user can change it if they want - OR we can simply redirect them back to the base URL)

3) Need to add link to the bottom of index.php which shows GIT version, like this:
![image](https://user-images.githubusercontent.com/8906637/30512045-ba421c78-9a9a-11e7-816f-f1c1e2bdd41f.png)

4) Need to possibly rethink the auto-generation of the images based on the user-defined link in conig.php.  SOME users may not use the most common names.  For example, I don't use "OMBI" (because no one knows what the F that stands for) - so IF I want the service title to be  "plex request" but show the OMBI icon, you'd have to define that.  

5) let's go ahead and merge PHP with Dev, and push dev to master. 

Thanks it for now, great work @jonfinley  @wjbeckett !!! SICK!

**Comment by wjbeckett** [comment]
PHP has been merged with Dev already. We were waiting till you were back to push to master @seanvree. 

@jonfinley and I had a conversation the other day about the use of service name and image. We were thinking that we can add another variable, but if we are going to build a settings page, then it would be defined there I guess. Something to think about as a team maybe. 

I can quite easily build the offline link into the PHP function, no issues there. We just need to decide where we are going to send it. 

I'll have a look at that bootstrap as well to see how we can auto space it. It can be done, just gotta find the right code.

**Comment by jonfinley** [comment]
Yo!

1. I'm pretty sure that should be easy to do, like @wjbeckett said, bootstrap i think is currently aligned left???? 
2. do you want a link or a symbol denoting that the link is broke??? As a standalone single page (minus the in thought process settings.php page) do you want hte users leaving the page to see that the link is broken???
3. easy....i think.... 

4. this coincides with the settings page, i think would be easiest. not to borrow from org, but similar to how org works think would be the best...i think....lol. this also means we need to figure out how to use databases with php 👅 

5.  done after this post....

💪

**Comment by seanvree** [comment]
2)  Well, the OFFLINE image already denotes that's it's down, but it will still be a hyperlink to the DOWN link, so we just need to point that link somewhere, either BACK to the index.php, or I would say let's create a quick offline page that the user can change via the settings.php page
