### ISSUE TITLE
FEAT: Add Branch ver and Github Link to Index

### ISSUE THREAD

**Issue by seanvree** [seanvree/Monitorr#17]
Need to add link to the bottom of index.php which shows GIT version, like this:
![image](https://user-images.githubusercontent.com/8906637/30512045-ba421c78-9a9a-11e7-816f-f1c1e2bdd41f.png)

**Comment by wjbeckett** [comment]
Can do this using the GitHub API.
https://developer.github.com/v3/repos/branches/#get-branch

**Comment by seanvree** [comment]
@wjbeckett  yup! Perfect!

**Comment by wjbeckett** [comment]
Completed in https://github.com/seanvree/Monitorr/commit/c686a45a5250e1394edc087846082c8fd8208776
