### ISSUE TITLE
BUG:  Clock "blink" due to refresh of service poll

### ISSUE THREAD

**Issue by seanvree** [seanvree/Monitorr#19]
Clock tile "blinks" due to refresh of services poll. I think we can roll the refresh of the time and the services into one action. I didn't look into that yet.

**Comment by wjbeckett** [comment]
What clock?

**Comment by wjbeckett** [comment]
This is going to have to go outside the loop.php. possibly on a separate row along with the server info. That way the loop refresh won't affect the clock or server resources tiles.

**Comment by seanvree** [comment]
@wjbeckett  oh really? Shoot, I was afraid of that.  

So the refresh is per ROW not the entire page?

**Comment by seanvree** [comment]
Resolved in Develop
