### ISSUE TITLE
BUG:  HTTPs links don't work

### ISSUE THREAD

**Issue by seanvree** [seanvree/Monitorr#31]
Issue:  HTTPs resources don't work / always reports OFFLINE. 

Status:  Investigating.

**Comment by Unimatrix0** [comment]
This is almost certainly due to use of an invalid SSL certificate.
For users who are unable to install a valid certificate, CURLOPT_SSL_VERIFYHOST can be set to 0 in check.php

**Comment by seanvree** [comment]
@Unimatrix0  - in my testing on my rig it's not. I have good certs and it always reports down.  Were you able to test on your rig with good certs?

As far as the work around- yeah! I think that's doable!

**Comment by wjbeckett** [comment]
I've never had issues with https links. Have been using them the beginning
when I was building the checks.

I've been using let'sencrypt certs.

Not sure what is up with your setup @seanvree but I believe @jonfinley is
using https links too.

**Comment by Unimatrix0** [comment]
@seanvree, Yep, tested by IP (cert doesn't have IP in SAN, so invalid), showed as dead. Tested by hostname (in SAN), showed as alive.

**Comment by seanvree** [comment]
Yeah, weird. I'm using LE certs as well.  I can access the same link in a browser with no errors, I'll continue to debug. May be a local DNS issue.

**Comment by seanvree** [comment]
not sure what fixed this, but in the recent changes, working on windows.
